import { LESSON_ISLAND_INSTRUMENTS } from '../constants/lessonIslandInstruments'
import { LESSON_ISLAND_LEVELS } from '../constants/lessonIslandLevels'

export const guitarHardLessonIslandScene = Object.freeze({
  id: 'guitar-hard',
  instrument: LESSON_ISLAND_INSTRUMENTS.GUITAR,
  level: LESSON_ISLAND_LEVELS.HARD,
  title: 'Guitar Island Hard',
  backHref: '/guitar_island',
  backLabel: 'Back to Guitar Island',
  canvas: {
    width: 2480,
    height: 1600,
    pageFill: 'linear-gradient(180deg, #78cd65 0%, #5ba85a 100%)',
    stageFill: '#63ab5d',
    stageShadow: '0 28px 64px rgba(18, 53, 26, 0.28)',
  },
  layers: [
    {
      id: 'background',
      src: '/images/islands-lesson/expert-difficulty/hard_background.png',
      left: -1.2,
      top: -2.8,
      width: 102.4,
      zIndex: 0,
    },
    {
      id: 'hammer_on_heights',
      src: '/images/islands-lesson/expert-difficulty/hammer_on_heights.png',
      left: 17,
      top: 7,
      width: 4.5,
      zIndex: 14,
    },
    {
      id: 'slide_sidewalk',
      src: '/images/islands-lesson/expert-difficulty/slide_sidewalk.png',
      left: 70,
      top: 11,
      width: 25,
      zIndex: 4,
    },
    {
      id: 'modal_mountain',
      src: '/images/islands-lesson/expert-difficulty/modal_mountain.png',
      left: 30,
      top: 77,
      width: 15,
      zIndex: 4,
    },
    {
      id: 'harmonic_harbor',
      src: '/images/islands-lesson/expert-difficulty/harmonic_harbor.png',
      left: 67,
      top: 73,
      width: 29,
      zIndex: 4,
    },
    {
      id: 'path',
      src: '/images/islands-lesson/expert-difficulty/hard_path.png',
      left: -3,
      top: -7,
      width: 97,
      zIndex: 12,
    },
    {
      id: 'finish_sign',
      src: '/images/islands-lesson/expert-difficulty/finish_sign.png',
      left: 5,
      top: 54,
      width: 12,
      zIndex: 20,
    },
    {
      id: 'hammer_on_heights_sign',
      src: '/images/islands-lesson/expert-difficulty/hammer_on_heights_sign.png',
      left: 23,
      top: 13,
      width: 9,
      zIndex: 20,
    },
    {
      id: 'slide_sidewalk_sign',
      src: '/images/islands-lesson/expert-difficulty/slide_sidewalk_sign.png',
      left: 88,
      top: 9,
      width: 8,
      zIndex: 3,
    },
    {
      id: 'modal_mountain_sign',
      src: '/images/islands-lesson/expert-difficulty/modal_mountain_sign.png',
      left: 28,
      top: 68,
      width: 8,
      zIndex: 20,
    },
    {
      id: 'sweep_coast_sign',
      src: '/images/islands-lesson/expert-difficulty/sweep_coast_sign.png',
      left: 54,
      top: 57,
      width: 5,
      zIndex: 20,
    },
    {
      id: 'harmonic_harbor_sign',
      src: '/images/islands-lesson/expert-difficulty/harmonic_harbor_sign.png',
      left: 85,
      top: 63,
      width: 10,
      zIndex: 20,
    },
  ],
  hotspots: [
    {
      id: 'modal_mountain',
      label: 'Open Modal Mountain lesson',
      title: 'Open Modal Mountain lesson',
      href: '/lesson',
      left: 29.4,
      top: 66.2,
      width: 16.3,
      height: 30.2,
      zIndex: 30,
    },
  ],
})
