import { LESSON_ISLAND_INSTRUMENTS } from '../constants/lessonIslandInstruments'
import { LESSON_ISLAND_LEVELS } from '../constants/lessonIslandLevels'

export const guitarMediumLessonIslandScene = Object.freeze({
  id: 'guitar-medium',
  instrument: LESSON_ISLAND_INSTRUMENTS.GUITAR,
  level: LESSON_ISLAND_LEVELS.MEDIUM,
  title: 'Guitar Island Medium',
  backHref: '/guitar_island',
  backLabel: 'Back to Guitar Island',
  canvas: {
    width: 2480,
    height: 1600,
    pageFill:
      'linear-gradient(180deg, #67b9dc 0%, #67b9dc 15%, #aec94d 15%, #61aa63 46%, #4d9157 100%)',
    stageFill: '#5ea35b',
    stageShadow: '0 28px 64px rgba(18, 53, 26, 0.28)',
  },
  layers: [
    {
      id: 'background',
      src: '/images/islands-lesson/medium-difficulty/medium_background.png',
      left: -2.4,
      top: -11.2,
      width: 104.8,
      zIndex: 0,
    },
    {
      id: 'alternate_alley',
      src: '/images/islands-lesson/medium-difficulty/alternate_alley.png',
      left: -2.8,
      top: 18,
      width: 21,
      zIndex: 4,
    },
    {
      id: 'finger_fret_fields',
      src: '/images/islands-lesson/medium-difficulty/finger_fret_fields.png',
      left: 18.1,
      top: 28.6,
      width: 33.8,
      zIndex: 4,
    },
    {
      id: 'chord_progression_plaza',
      src: '/images/islands-lesson/medium-difficulty/chord_progression_plaza.png',
      left: 56,
      top: 10,
      width: 30,
      zIndex: 4,
    },
    {
      id: 'scale_summit',
      src: '/images/islands-lesson/medium-difficulty/scale_summit.png',
      left: 73,
      top: 68,
      width: 15,
      zIndex: 14,
    },
    {
      id: 'bare_borough',
      src: '/images/islands-lesson/medium-difficulty/bare_borough.png',
      left: 0,
      top: 65,
      width: 30,
      zIndex: 4,
    },
    {
      id: 'path',
      src: '/images/islands-lesson/medium-difficulty/medium_path.png',
      left: 5,
      top: -5,
      width: 102,
      zIndex: 12,
    },
    {
      id: 'alternate_alley_sign',
      src: '/images/islands-lesson/medium-difficulty/alternate_alley_sign.png',
      left: 14.7,
      top: 21,
      width: 4,
      zIndex: 20,
    },
    {
      id: 'finger_fret_fields_sign',
      src: '/images/islands-lesson/medium-difficulty/finger_fret_fields_sign.png',
      left: 26.8,
      top: 31.4,
      width: 7.6,
      zIndex: 20,
    },
    {
      id: 'chord_progression_plaza_sign',
      src: '/images/islands-lesson/medium-difficulty/chord_progression_plaza_sign.png',
      left: 56,
      top: 10,
      width: 10,
      zIndex: 20,
    },
    {
      id: 'finish_sign',
      src: '/images/islands-lesson/medium-difficulty/finish_sign.png',
      left: 84.3,
      top: 22.9,
      width: 13.7,
      zIndex: 20,
    },
    {
      id: 'scale_summit_sign',
      src: '/images/islands-lesson/medium-difficulty/scale_summit_sign.png',
      left: 65,
      top: 75,
      width: 6.5,
      zIndex: 20,
    },
    {
      id: 'bare_borough_sign',
      src: '/images/islands-lesson/medium-difficulty/bare_borough_sign.png',
      left: 2,
      top: 78,
      width: 11,
      zIndex: 20,
    },
  ],
  hotspots: [
    {
      id: 'bare_borough',
      label: 'Open Bare Borough lesson',
      title: 'Open Bare Borough lesson',
      href: '/lesson',
      left: 0,
      top: 69.5,
      width: 28.5,
      height: 22.8,
      zIndex: 30,
    },
  ],
})
