import { LESSON_ISLAND_INSTRUMENTS } from '../constants/lessonIslandInstruments'
import { LESSON_ISLAND_LEVELS } from '../constants/lessonIslandLevels'

export const guitarBeginnerLessonIslandScene = Object.freeze({
  id: 'guitar-beginner',
  instrument: LESSON_ISLAND_INSTRUMENTS.GUITAR,
  level: LESSON_ISLAND_LEVELS.BEGINNER,
  title: 'Guitar Island Beginner',
  backHref: '/guitar_island',
  backLabel: 'Back to Guitar Island',
  canvas: {
    width: 2480,
    height: 1600,
    pageFill:
      'linear-gradient(180deg, #67b9dc 0%, #67b9dc 15%, #aec94d 15%, #61aa63 46%, #4d9157 100%)',
    stageFill: '#5ea35b',
    stageShadow: '0 28px 64px rgba(18, 53, 26, 0.28)',
  },
  layers: [
    {
      id: 'background',
      src: '/images/islands-lesson/background.png',
      left: -2.4,
      top: -11.2,
      width: 104.8,
      zIndex: 0,
    },
    {
      id: 'rhythm-ranch-terrain',
      src: '/images/islands-lesson/rhythm_ranch_path.png',
      left: 27,
      top: 10,
      width: 21,
      zIndex: 4,
    },
    {
      id: 'melody-meadows',
      src: '/images/islands-lesson/melody_meadows.png',
      left: 73,
      top: 15,
      width: 32,
      zIndex: 4,
    },
    {
      id: 'strum-street-road',
      src: '/images/islands-lesson/strum_street_path.png',
      left: 37,
      top: 27,
      width: 55,
      zIndex: 4,
    },
    {
      id: 'chord-corner-road',
      src: '/images/islands-lesson/chord_corner.png',
      left: 15,
      top: 65,
      width: 29,
      zIndex: 4,
    },
    {
      id: 'tuner-town-road',
      src: '/images/islands-lesson/tuner_town_path.png',
      left: 57.8,
      top: 65,
      width: 35.2,
      zIndex: 4,
    },
    {
      id: 'path',
      src: '/images/islands-lesson/path.png',
      left: -1.6,
      top: -3.2,
      width: 98.9,
      zIndex: 12,
    },
    {
      id: 'finish-sign',
      src: '/images/islands-lesson/finish_sign.png',
      left: 3.2,
      top: 24.7,
      width: 13.6,
      zIndex: 20,
    },
    {
      id: 'rhythm-ranch-sign',
      src: '/images/islands-lesson/rhythm_ranch_sign.png',
      left: 35,
      top: 23,
      width: 5,
      zIndex: 20,
    },
    {
      id: 'strum-street-sign',
      src: '/images/islands-lesson/strum_street_sign.png',
      left: 55.1,
      top: 25,
      width: 10,
      zIndex: 3,
    },
    {
      id: 'chord-corner-building',
      src: '/images/islands-lesson/chord_corner_sign.png',
      left: 18,
      top: 66,
      width: 10,
      zIndex: 20,
    },
    {
      id: 'tuner-town-sign',
      src: '/images/islands-lesson/tuner_town_sign.png',
      left: 86.9,
      top: 70.7,
      width: 6.8,
      zIndex: 20,
    },
  ],
  hotspots: [
    {
      id: 'chord-corner',
      label: 'Open Chord Corner lesson',
      title: 'Open Chord Corner lesson',
      href: '/lesson',
      left: 7.9,
      top: 70.8,
      width: 16.5,
      height: 21.4,
      zIndex: 30,
    },
  ],
})
